# Generated by Django 3.2.9 on 2022-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_age',
            field=models.PositiveSmallIntegerField(default=15, help_text='This is the age that will be used to generate quizzes and questions to you!'),
        ),
    ]
