# Generated by Django 3.2.9 on 2022-07-06 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20220621_2156'),
        ('question', '0003_alter_fourchoicesquestion_correct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20220621_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoriteUsers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoriteUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourChoicesQuestions_created',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestionsCreated', to='question.FourChoicesQuestion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quizzes_created',
            field=models.ManyToManyField(blank=True, related_name='quizzesCreated', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trueOrFalseQuestions_created',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalseQuestionsCreated', to='question.TrueOrFalseQuestion'),
        ),
    ]
