# Generated by Django 3.2.9 on 2022-07-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220707_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteUsers',
            new_name='favoriteUser',
        ),
    ]
