# Generated by Django 3.2.9 on 2022-07-28 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_profile_last_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fourChoicesQuestions_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quizzes_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trueOrFalseQuestions_created',
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
