# Generated by Django 3.2.9 on 2022-08-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_composition'),
        ('core', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_quizzes',
            field=models.ManyToManyField(blank=True, related_name='recommended_profiles', to='quiz.Quiz'),
        ),
    ]
