# Generated by Django 3.2.9 on 2022-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_trueorfalsequestion_correct'),
        ('quiz', '0008_alter_quiz_categories'),
        ('core', '0011_profile_recommended_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_four_choices_questions',
            field=models.ManyToManyField(blank=True, related_name='recommended_four_choices_questions_profiles', to='question.FourChoicesQuestion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommended_true_or_false_questions',
            field=models.ManyToManyField(blank=True, related_name='recommended_true_or_false_questions_profiles', to='question.TrueOrFalseQuestion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommended_quizzes',
            field=models.ManyToManyField(blank=True, related_name='recommended_quizzes_profiles', to='quiz.Quiz'),
        ),
    ]
