# Generated by Django 3.2.9 on 2022-08-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220806_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='HTTP_SEC_CH_UA',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='HTTP_SEC_CH_UA_PLATFORM',
            field=models.CharField(default='platform', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='HTTP_USER_AGENT',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
