# Generated by Django 3.2.9 on 2022-08-10 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0007_fourchoicesattempter_trueorfalseattempter'),
        ('core', '0013_auto_20220807_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_four_choices_questions',
            field=models.ManyToManyField(blank=True, related_name='following_four_choices_questions_profiles', to='question.FourChoicesQuestion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_true_or_false_questions',
            field=models.ManyToManyField(blank=True, related_name='following_true_or_false_questions_profiles', to='question.TrueOrFalseQuestion'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
