# Generated by Django 3.2.9 on 2022-10-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_quiz_user'),
        ('q', '0010_auto_20220925_2349'),
        ('room', '0002_auto_20221003_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='studyroom',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='q.Q'),
        ),
    ]
