# Generated by Django 3.2.9 on 2022-10-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_quiz_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0015_auto_20220920_1353'),
        ('q', '0010_auto_20220925_2349'),
        ('room', '0003_auto_20221003_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyroom',
            name='fourChoicesQuestions',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='members',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='trueOrFalseQuestions',
        ),
        migrations.CreateModel(
            name='RoomTrueOrFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueOrFalseQuestion_sponsored', to=settings.AUTH_USER_MODEL)),
                ('trueOrFalseQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='question.trueorfalsequestion')),
            ],
        ),
        migrations.CreateModel(
            name='RoomQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='quiz.quiz')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_sponsored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='q.q')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_sponsored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFourChoicesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fourChoicesQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='question.fourchoicesquestion')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourChoicesQuestion_sponsored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
