# Generated by Django 3.2.9 on 2022-05-29 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('when', models.CharField(default='', max_length=200)),
                ('lastQuestionIndex', models.PositiveSmallIntegerField(default=0)),
                ('questionLength', models.PositiveSmallIntegerField(default=0)),
                ('totalScore', models.PositiveSmallIntegerField(default=0)),
                ('shuffleQuestions', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('public', models.BooleanField(default=True)),
                ('duration', models.PositiveSmallIntegerField(default=30)),
                ('get_duration', models.CharField(default='', max_length=200)),
                ('solution_quality', models.IntegerField(default=0)),
                ('likeCount', models.PositiveIntegerField(default=0)),
                ('age_from', models.PositiveSmallIntegerField(null=True, verbose_name='Minimum Age Of Quiz Takers')),
                ('age_to', models.PositiveSmallIntegerField(null=True, verbose_name='Maximum Age Of Quiz Takers')),
                ('relevance', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', related_query_name='categories', to='category.Category')),
                ('fourChoicesQuestions', models.ManyToManyField(blank=True, related_name='fourChoicesQuestions', related_query_name='fourChoicesQuestions', to='question.FourChoicesQuestion')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('solution_validators', models.ManyToManyField(blank=True, related_name='quiz_solution_validators', to=settings.AUTH_USER_MODEL)),
                ('trueOrFalseQuestions', models.ManyToManyField(blank=True, related_name='trueOrFalseQuestions', related_query_name='trueOrFalseQuestions', to='question.TrueOrFalseQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuizLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('link', models.URLField(verbose_name='Link/URL')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('ban', models.BooleanField(default=False)),
                ('reportCount', models.PositiveSmallIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('quiz', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quizlink', to='quiz.quiz')),
                ('reporters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attempter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('timeTaken', models.PositiveSmallIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-percentage', '-score', 'timeTaken'],
            },
        ),
    ]
