# Generated by Django 3.2.9 on 2022-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='get_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='when',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
