# Generated by Django 3.2.9 on 2022-05-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_get_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='when',
            field=models.CharField(default='', max_length=200),
        ),
    ]
