# Generated by Django 3.2.9 on 2022-07-28 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_quiz_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='fourChoicesQuestions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='trueOrFalseQuestions',
        ),
        migrations.AlterField(
            model_name='attempter',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempters', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='attempter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempters', to=settings.AUTH_USER_MODEL),
        ),
    ]
