# Generated by Django 3.2.9 on 2022-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220728_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='composition',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Composition'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
