# Generated by Django 3.2.9 on 2022-07-30 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20220730_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='composition',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Description'),
        ),
    ]
