# Generated by Django 3.2.9 on 2022-08-04 23:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220730_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='composition',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Composition and Instructions'),
        ),
    ]
