# Generated by Django 3.2.9 on 2022-08-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('quiz', '0007_alter_quiz_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='category.Category'),
        ),
    ]
