# Generated by Django 3.2.9 on 2022-08-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
