# Generated by Django 3.2.9 on 2022-08-28 21:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='age_from',
            field=models.PositiveSmallIntegerField(default=11, verbose_name='Minimum Age Of Quiz Takers'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='age_to',
            field=models.PositiveSmallIntegerField(default=65, verbose_name='Maximum Age Of Quiz Takers'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
