# Generated by Django 3.2.9 on 2022-05-29 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('relevance', models.FloatField(default=0)),
                ('detailpageviews', models.PositiveIntegerField(default=0)),
                ('detailpageclicks', models.PositiveIntegerField(default=0)),
                ('detailpagerelevance', models.FloatField(default=0)),
                ('submitpageviews', models.PositiveIntegerField(default=0)),
                ('submitpageclicks', models.PositiveIntegerField(default=0)),
                ('submitpagerelevance', models.FloatField(default=0)),
                ('bannerpageviews', models.PositiveIntegerField(default=0)),
                ('bannerpageclicks', models.PositiveIntegerField(default=0)),
                ('bannerpagerelevance', models.FloatField(default=0)),
                ('correctionpageviews', models.PositiveIntegerField(default=0)),
                ('correctionpageclicks', models.PositiveIntegerField(default=0)),
                ('correctionpagerelevance', models.FloatField(default=0)),
                ('clickers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
