# Generated by Django 3.2.9 on 2022-07-30 20:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='dashboard_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postad',
            name='clickers',
            field=models.ManyToManyField(blank=True, related_name='clicked_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postad',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/ads/'),
        ),
    ]
