# Generated by Django 3.2.9 on 2022-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fourchoicesquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trueorfalsequestion',
            options={},
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='correct',
            field=models.CharField(choices=[('First Option', 'answer1'), ('Second Option', 'answer2'), ('Third Option', 'answer3'), ('Fourth Option', 'answer4')], max_length=100, verbose_name='Correct Option'),
        ),
    ]
