# Generated by Django 3.2.9 on 2022-06-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220627_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='correct',
            field=models.CharField(choices=[('answer1', 'First Option'), ('answer2', 'Second Option'), ('answer3', 'Third Option'), ('answer4', 'Fourth Option')], max_length=100, verbose_name='Correct Option'),
        ),
    ]
