# Generated by Django 3.2.9 on 2022-07-30 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20220728_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='question',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='question',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Solution'),
        ),
    ]
