# Generated by Django 3.2.9 on 2022-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20220730_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='correct',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=100, verbose_name='Correct Option'),
        ),
    ]
