# Generated by Django 3.2.9 on 2022-08-07 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0006_alter_trueorfalsequestion_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueOrFalseAttempter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetaken', models.PositiveSmallIntegerField(null=True)),
                ('correct', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ManyToManyField(blank=True, related_name='attempters', to='question.TrueOrFalseQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_true_or_false_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FourChoicesAttempter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetaken', models.PositiveSmallIntegerField(null=True)),
                ('correct', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ManyToManyField(blank=True, related_name='attempters', to='question.FourChoicesQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_four_choices_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
