# Generated by Django 3.2.9 on 2022-08-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('question', '0007_fourchoicesattempter_trueorfalseattempter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='fourChoicesQuestions', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='trueOrFalseQuestions', to='category.Category'),
        ),
    ]
