# Generated by Django 3.2.9 on 2022-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_alter_fourchoicesquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='duration_in_seconds',
            field=models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180), (185, 185), (190, 190), (195, 195), (200, 200), (205, 205), (210, 210), (215, 215), (220, 220), (225, 225), (230, 230), (235, 235), (240, 240), (245, 245), (250, 250), (255, 255), (260, 260), (265, 265), (270, 270), (275, 275), (280, 280), (285, 285), (290, 290), (295, 295), (300, 300)], default=30, verbose_name='Duration In Seconds'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='standalone',
            field=models.BooleanField(default=True, verbose_name='Create as an OldTownRoad question too'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='duration_in_seconds',
            field=models.PositiveSmallIntegerField(choices=[(15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60), (65, 65), (70, 70), (75, 75), (80, 80), (85, 85), (90, 90), (95, 95), (100, 100), (105, 105), (110, 110), (115, 115), (120, 120), (125, 125), (130, 130), (135, 135), (140, 140), (145, 145), (150, 150), (155, 155), (160, 160), (165, 165), (170, 170), (175, 175), (180, 180), (185, 185), (190, 190), (195, 195), (200, 200), (205, 205), (210, 210), (215, 215), (220, 220), (225, 225), (230, 230), (235, 235), (240, 240), (245, 245), (250, 250), (255, 255), (260, 260), (265, 265), (270, 270), (275, 275), (280, 280), (285, 285), (290, 290), (295, 295), (300, 300)], default=30, verbose_name='Duration In Seconds'),
        ),
    ]
