# Generated by Django 3.2.9 on 2022-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20220820_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='age_from',
            field=models.PositiveSmallIntegerField(default=11, verbose_name='Minimum Age Of Quiz Takers'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='age_to',
            field=models.PositiveSmallIntegerField(default=65, verbose_name='Maximum Age Of Quiz Takers'),
        ),
    ]
