# Generated by Django 3.2.9 on 2022-08-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20220828_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='age_from',
            field=models.PositiveSmallIntegerField(default=11, verbose_name='Minimum Age Of Quiz Takers'),
        ),
        migrations.AlterField(
            model_name='fourchoicesquestion',
            name='age_to',
            field=models.PositiveSmallIntegerField(default=65, verbose_name='Maximum Age Of Quiz Takers'),
        ),
    ]
