# Generated by Django 3.2.9 on 2022-09-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20220828_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoicesquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trueorfalsequestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
