# Generated by Django 3.2.9 on 2022-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='question',
            field=models.TextField(max_length=10000, unique=True, verbose_name='Question'),
        ),
    ]
