# Generated by Django 3.2.9 on 2022-07-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0002_auto_20220723_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='q',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='q',
            name='question',
            field=models.CharField(max_length=200, unique=True, verbose_name='Question'),
        ),
    ]
