# Generated by Django 3.2.9 on 2022-07-23 03:55

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0003_auto_20220723_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 23, 3, 54, 19, 113726, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='a',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='q',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='q',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
