# Generated by Django 3.2.9 on 2022-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0004_auto_20220723_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q',
            name='description',
            field=models.TextField(default='This is the default description', max_length=1000),
            preserve_default=False,
        ),
    ]
