# Generated by Django 3.2.9 on 2022-07-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('core', '0007_profile_last_question_date'),
        ('q', '0005_alter_q_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='a',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='a',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='q',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='q',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='q',
            name='voters',
        ),
        migrations.AddField(
            model_name='a',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_answers', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='a',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_answers', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='q',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_questions', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='q',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_questions', to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='q',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='qs', to='category.Category'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='q.a')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.profile')),
            ],
        ),
    ]
