# Generated by Django 3.2.9 on 2022-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0006_auto_20220727_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
