# Generated by Django 3.2.9 on 2022-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0007_alter_q_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q',
            options={'ordering': ['-date', '-date_updated']},
        ),
        migrations.AddField(
            model_name='q',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
