# Generated by Django 3.2.9 on 2022-08-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0008_auto_20220802_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=1000),
        ),
    ]
