# Generated by Django 3.2.9 on 2022-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0009_alter_reply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/qxa/answer/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='q',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/qxa/question/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='q',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
