# Generated by Django 3.2.9 on 2022-03-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_auto_20220306_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakLeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('week', models.PositiveSmallIntegerField(default=0)),
                ('leaders', models.ManyToManyField(related_name='leaders', to='core.Streak')),
            ],
        ),
    ]
